export const PATHS = {
    root: '/',
    login: '/login',
    plants: '/plants',
    plant: '/plants/:id',
    addPlant: '/add-plant',
    editPlant: 'plants/:id/edit',
    rooms: '/rooms',
    room: '/rooms/:id',
    addRoom: '/add-room',
    editRoom: 'rooms/:id/edit',
    sensors: '/sensors',
    sensor: '/sensors/:id',
    addSensor: '/add-sensor',
  };